# Generated by Django 2.2.6 on 2020-01-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.CharField(max_length=120)),
                ('link', models.CharField(max_length=120)),
                ('organizer', models.CharField(max_length=120)),
            ],
        ),
    ]
