# Generated by Django 2.2.6 on 2020-01-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='link',
            field=models.CharField(default='none', max_length=120),
        ),
    ]
